### PR TITLE
Port to async introspection and GUPnP 1.2

### LINKED ISSUE #166: 0.6.0: does not build against gupnp 1.2
<pre>[tkloczko@domek dleyna-renderer-0.6.0]$ make
make  all-recursive
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0&apos;
Making all in libdleyna/renderer
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0/libdleyna/renderer&apos;
/bin/sh ../../libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dleyna-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gupnp-1.2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2  -I/usr/include/gssdp-1.2  -I/usr/include/gupnp-1.2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libsoup-2.4 -I/usr/include/libxml2  -I/usr/include/gupnp-av-1.0  -I/usr/include/gupnp-dlna-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread  -I/usr/include/libsoup-2.4 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -include config.h -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -Wno-format-extra-args -Wl,--no-undefined -version-info 1:3:0 -no-undefined -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto -fuse-linker-plugin -o libdleyna-renderer-1.0.la -rpath /usr/lib64/dleyna-renderer  async.lo device.lo host-service.lo manager.lo server.lo task.lo upnp.lo -lglib-2.0  -lgio-2.0 -lgobject-2.0 -lglib-2.0  -ldleyna-core-1.0 -Wl,--export-dynamic -pthread -lgmodule-2.0 -lgupnp-1.2 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lxml2  -lgssdp-1.2  -lgupnp-1.2 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lxml2  -lgupnp-av-1.0  -lgupnp-dlna-2.0 -lgobject-2.0 -lglib-2.0  -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lm 
libtool: link: gcc -shared  -fPIC -DPIC  .libs/async.o .libs/device.o .libs/host-service.o .libs/manager.o .libs/server.o .libs/task.o .libs/upnp.o  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -pthread -pthread -O2 -g -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -flto -Os -Wl,--no-undefined -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -flto -fuse-linker-plugin -Wl,--export-dynamic -pthread   -pthread  -ldleyna-core-1.0 -lgmodule-2.0 -lgssdp-1.2 -lgupnp-1.2 -lxml2 -lgupnp-av-1.0 -lgupnp-dlna-2.0 -lsoup-2.4 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lm -Wl,-soname -Wl,libdleyna-renderer-1.0.so.1 -o .libs/libdleyna-renderer-1.0.so.1.0.3
/usr/bin/ld: /tmp/libdleyna-renderer-1.0.so.1.0.3.cSmCjy.ltrans0.ltrans.o: in function `prv_props_update.isra.0&apos;:
/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0/libdleyna/renderer/device.c:2150: undefined reference to `gupnp_service_info_get_introspection&apos;
/usr/bin/ld: /home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0/libdleyna/renderer/device.c:2218: undefined reference to `gupnp_service_info_get_introspection&apos;
/usr/bin/ld: /tmp/libdleyna-renderer-1.0.so.1.0.3.cSmCjy.ltrans0.ltrans.o: in function `prv_server_unavailable_cb&apos;:
/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0/libdleyna/renderer/upnp.c:247: undefined reference to `gupnp_context_get_host_ip&apos;
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:502: libdleyna-renderer-1.0.la] Error 1
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0/libdleyna/renderer&apos;
make[1]: *** [Makefile:442: all-recursive] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0&apos;
</pre>

### PR DESCRIPTION
**Pull request by phako**
Also fix a log message to be english, not french. Ideally gasync-task.[ch] should be in dleyna-core, though.

Should fix the issue with sometimes not shutting down properly

Fixes #166

### CODE REVIEW

**Comment by phako** [comment]
There is an issue on shutdown where it crashes in the linux context manager when used with 1.2. That still needs fixing

**Comment by phako** [comment]
crash is gone. was caused by bad linking on my machine

**Comment by kloczek** [comment]
Looks like still something is missing
<pre>/bin/sh ../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../..    -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -I/usr/include/dleyna-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gupnp-1.2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2  -I/usr/include/gssdp-1.2  -I/usr/include/gupnp-1.2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libsoup-2.4 -I/usr/include/libxml2  -I/usr/include/gupnp-av-1.0  -I/usr/include/gupnp-dlna-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread  -I/usr/include/libsoup-2.4 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include  -include config.h -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -Wno-format-extra-args -Wl,--no-undefined -c -o gasync-task.lo gasync-task.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../.. -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/dleyna-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/gupnp-1.2 -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gssdp-1.2 -I/usr/include/gupnp-1.2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/libsoup-2.4 -I/usr/include/libxml2 -I/usr/include/gupnp-av-1.0 -I/usr/include/gupnp-dlna-2.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -pthread -I/usr/include/libsoup-2.4 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -include config.h -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -flto -Os -Wno-format-extra-args -Wl,--no-undefined -c gasync-task.c  -fPIC -DPIC -o .libs/gasync-task.o
<b>gasync-task.c:22:10:</b> <font color="#CC0000"><b>fatal error: </b></font>task-processor.h: No such file or directory
   22 | #include <font color="#CC0000"><b>&quot;task-processor.h&quot;</b></font>
      |          <font color="#CC0000"><b>^~~~~~~~~~~~~~~~~~</b></font>
compilation terminated.
make[2]: *** [Makefile:550: gasync-task.lo] Error 1
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0/libdleyna/renderer&apos;
make[1]: *** [Makefile:442: all-recursive] Error 1
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/dleyna-renderer-0.6.0&apos;
make: *** [Makefile:374: all] Error 2
error: Bad exit status from /var/tmp/rpm-tmp.irm4w7 (%build)
</pre>

**Comment by kloczek** [comment]
Here is build fix.
```
--- a/libdleyna/renderer/Makefile.am~	2019-10-29 23:19:39.000000000 +0000
+++ b/libdleyna/renderer/Makefile.am	2019-10-29 23:31:28.842665044 +0000
@@ -37,6 +38,15 @@
 					$(GUPNPDLNA_LIBS) 	\
 					$(SOUP_LIBS)		\
 					-lm
+libdleyna_renderer_1_0_la_CFLAGS =	$(GLIB_CFLAGS)		\
+					$(GIO_CFLAGS)		\
+					$(DLEYNA_CORE_CFLAGS)	\
+					$(GSSDP_CFLAGS)		\
+					$(GUPNP_CFLAGS)		\
+					$(GUPNPDLNA_CFLAGS)	\
+					$(GUPNPAV_CFLAGS)	\
+					$(SOUP_CFLAGS)		\
+					-include config.h
 
 MAINTAINERCLEANFILES =	Makefile.in		\
 			aclocal.m4		\
--- a/libdleyna/renderer/gasync-task.c~	2019-10-29 23:52:22.000000000 +0000
+++ b/libdleyna/renderer/gasync-task.c	2019-10-29 23:55:30.438411905 +0000
@@ -19,7 +19,7 @@
  */
 
 #include "gasync-task.h"
-#include "task-processor.h"
+#include <libdleyna/core/task-processor.h>
 
 struct dleyna_gasync_task_t_ {
 	dleyna_task_atom_t base;


```

**Comment by phako** [comment]
Sorry I messed up my branches, the new clean pull request is now #168

**Pull request closed without merging**
